/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HealthScoreGauge: typeof import('./components/HealthScoreGauge.vue')['default']
    PinDisplayModal: typeof import('./components/PinDisplayModal.vue')['default']
    RadarChart: typeof import('./components/RadarChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScanRow: typeof import('./components/ScanRow.vue')['default']
    SidebarLayout: typeof import('./components/SidebarLayout.vue')['default']
    StatCard: typeof import('./components/StatCard.vue')['default']
  }
}
